### ISSUE TITLE
Help setting up

### ISSUE THREAD

**Issue by ghost** [jasoncodes/tosr0x-http#1]
Hello.  So I loaded all the code and scripts into my ubuntu server to control my two relay module via wifi, but I can't seem to figure out how to set my device address in the code.  This is my first time using anything in node or js.  Which file do I need to edit to set my device IP address?

Thanks

**Comment by jasoncodes** [comment]
If you run `bin/tosr0x-http` without any arguments you should get usage instructions. The option you are after is `--device-host`. You can call it like `bin/tosr0x-http --device-host=192.0.2.1`

**Comment by jasoncodes** [comment]
I should add that if you install the npm module globally (with `npm install -g tosr0x-http`) then `tosr0x-http` will be in your `PATH` and you can use `tosr0x-http --device-host=192.0.2.1`.

You’ll probably want to setup a systemd unit to run the service in the background.

**Comment by ghost** [comment]
well I'm getting closer.  when I open the index.html file in my browser, I get "error toggling relay" and watching terminal it connects and disconnects, but it's also spitting out "Expected TOSR0X module ID"

**Comment by jasoncodes** [comment]
Have you successfully used `telnet 192.0.2.1 2000` to connect to the module and trigger relay state changes? For example, pressing `e` and `o` should turn relay 1 on and off. You can find the list of commands at http://www.tinyosshop.com/index.php?route=product/product&path=141_143&product_id=367.

“Expected TOSR0X module ID” indicates that sending a `Z` is not returning 15 as the module ID as documented in the table linked above. After rebooting the module I find sometimes this happens but it comes good after the the server reconnects. It should stay connected with only occasional temporary disconnects due to network issues.

If you are able to control the relay using `telnet`, I suggest trying to capture a packet log using `tcpdump` or Wireshark to further diagnose what is going on. If you would like me to review any logs, please upload them here as either pcap files or as a conversation hex dump.

**Comment by ghost** [comment]
Well I finally got time to get back on this.  I can successfully send telnet commands to the module, but I still get errors commanding the relays via the webpage.  Good news is that I tried a different approach by using node-red on my raspberry pi and when I linked up an inject block to a tcp ouput block it works!  I know using node-red is a lazy way of doing this, but for a code illiterate person like me at least it gives me a starting point.

**Comment by jasoncodes** [comment]
Node-RED sounds cool and seems like a good way to go about it.

I’d be more than happy to continue investigating this if you can provide traffic logs between the pi and relay module. I only have a single TOSR04-T module and it is working fine.
